service: tangential
frameworkVersion: '3'

plugins:
- serverless-offline
- serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler

  hello:
    handler: src/functions/hello.handler
    events:
    - http:
        method: get
        path: hello

  oauth:
    handler: src/functions/oauth.handler
    events:
    - http:
        method: get
        path: auth