service: tangential
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-offline-sqs

useDotenv: true
package:
  individually: ${self:custom.packageIndividually.${self:provider.stage}, true}

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 600
  stage: ${opt:stage, 'offline'}
  region: us-east-1
  iam:
    role:
      statements: ${file(./iam-role.yml)}

  environment:
    jiraAnalysisQueueUrl: ${self:custom.jiraAnalysisQueueUrl.${self:provider.stage}, self:custom.jiraAnalysisQueueUrl.remote}
    updateProjectAnalysisStatusQueueUrl: ${self:custom.updateProjectAnalysisStatusQueueUrl.${self:provider.stage}, self:custom.updateProjectAnalysisStatusQueueUrl.remote}
    MONGODB_DATABASE: tangential-${opt:stage}

  httpApi:
    cors:
      allowedOrigins:
        - "https://${self:provider.stage}.tangential.app"
        - "https://tangential.eu.ngrok.io"
      allowedHeaders:
        - "Content-Type"
        - "X-Atlassian-Token"
        - "X-Atlassian-Refresh-Token"
        - "X-Atlassian-Workspace-Id"
      allowCredentials: false

custom:
  packageIndividually:
    offline: false

  jiraAnalysisQueueUrl:
    offline: ${self:custom.serverless-offline-sqs.endpoint}/queue/JiraAnalysisQueue-${self:provider.stage}
    remote:
      Ref: JiraAnalysisQueue

  updateProjectAnalysisStatusQueueUrl:
    offline: ${self:custom.serverless-offline-sqs.endpoint}/queue/UpdateProjectAnalysisStatusQueueFifo-${self:provider.stage}.fifo
    remote:
      Ref: UpdateProjectAnalysisStatusQueueFifo

  serverless-offline-sqs:
    endpoint: http://localhost:4566
    region: us-east-1
    debug: true

  customDomain:
    domainName: ${self:provider.stage}.api.tangential.app
    stage: $default
    certificateArn: arn:aws:acm:us-east-1:556167323904:certificate/ba19fbb2-0c34-4cd6-984a-0c5562fd6e9d
    endpointType: regional
    hostedZoneId: Z091731134YSQCRRMM86I
    apiType: http
    autoDomain: true

functions:
  startWorkspaceAnalysis:
    handler: src/functions/startWorkspaceAnalysis.handler
    events:
      - httpApi:
          method: get
          path: /workspace/analyze

  analysisQueueHandler:
    handler: src/functions/analysisQueueHandler.handler
    events:
      - sqs:
          arn: !GetAtt JiraAnalysisQueue.Arn
          batchSize: 5

  updateProjectAnalysisStatusQueueHandler:
    handler: src/functions/updateProjectAnalysisStatus.handler
    events:
      - sqs:
          arn: !GetAtt UpdateProjectAnalysisStatusQueueFifo.Arn
          batchSize: 5

resources:
  Resources:
    JiraAnalysisQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JiraAnalysisQueue-${self:provider.stage}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt JiraAnalysisDeadLetterQueue.Arn
          maxReceiveCount: 2
        VisibilityTimeout: ${self:provider.timeout}

    JiraAnalysisDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JiraAnalysisDeadLetterQueue-${self:provider.stage}

    UpdateProjectAnalysisStatusQueueFifo:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UpdateProjectAnalysisStatusQueueFifo-${self:provider.stage}.fifo
        VisibilityTimeout: ${self:provider.timeout}
        FifoQueue: true
        ContentBasedDeduplication: true
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt UpdateProjectAnalysisStatusDeadLetterQueueFifo.Arn
          maxReceiveCount: 2

    UpdateProjectAnalysisStatusDeadLetterQueueFifo:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UpdateProjectAnalysisStatusDeadLetterQueueFifo-${self:provider.stage}.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
