service: tangential
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - "@akfreas/serverless-offline-sqs"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: tangential
  timeout: 60
  stage: ${opt:stage, 'offline'}
  region: us-east-1
  environment:
    projectAnalysisQueueUrl: ${self:custom.projectAnalysisQueueUrl.${self:provider.stage}, self:custom.projectAnalysisQueueUrl.remote}
custom:
  projectAnalysisQueueUrl:
    offline: ${self:custom.serverless-offline-sqs.endpoint}/queue/ProjectAnalysisQueue-${self:provider.stage}
    remote:
      Ref: ProjectAnalysisQueue
  serverless-offline-sqs:
    endpoint: http://localhost:4566
    region: us-east-1
    debug: true

functions:
  startWorkspaceAnalysis:
    handler: src/functions/startWorkspaceAnalysis.handler
    events:
      - http:
          method: get
          path: /workspace/analyze

  analyzeProjectFromQueue:
    handler: src/functions/analyzeProjectFromQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ProjectAnalysisQueue
              - Arn
          batchSize: 5

resources:
  Resources:
    ProjectAnalysisQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ProjectAnalysisQueue-${self:provider.stage}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ProjectAnalysisDeadLetterQueue.Arn
          maxReceiveCount: 2
        VisibilityTimeout: ${self:provider.timeout}

    ProjectAnalysisDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ProjectAnalysisDeadLetterQueue-${self:provider.stage}
